# SwiftCompilationError(error: call can throw, but it is not marked with 'try')

let result = AKt.foo()

exit(result)
